import './layout.scss'
import '../__assets/global.scss'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="nav">
          <div className='content_nav'>
              <h1>Instagram</h1>

              <div className="actions">
                <a href="/"><img src="unselected_icon/home.svg"/>Hjem</a>
                <a href="/"><img src="unselected_icon/search.svg"/>Søk</a>
                <a href="/"><img src="unselected_icon/create_new.svg"/>Opprett</a>
                <a href="/"><img src="unselected_icon/profile.svg"/>Profile</a>

                <button className="logout"><img src="unselected_icon/logout.svg"/>Logg ut</button>
              </div>
          </div>
        </div>

        {children}
      </body>
    </html>
  )
}
