services:   
  db:
    container_name: pg_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: instagram
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

  server:
    build:
      context: .
    depends_on:
      - db
    environment:
      DATABASE_URL: file:./dev.db
    ports:
      - 3000:3000
    
volumes:
  postgres-data: